### PR TITLE
Move reader to within retry loop, means it will work after first request

### PR DESCRIPTION
**Pull request by patrickmcguire**
Hey, this fixes the issue I've been having.

My go knowledge is limited, but from what I've been able to understand the reader doesn't reset automatically. The post retries from the end and there's nothing to send.

### CODE REVIEW

**Review by f2prateek — APPROVED** [review]

**Comment by srthurman** [comment]
@f2prateek ok to merge this PR, or is additional work/testing needed?

**Comment by srthurman** [comment]
@f2prateek ok to merge this PR, or is additional work/testing needed?

**Comment by f2prateek** [comment]
I don't really work on this codebase, but the changes look good to me.

cc @tejasmanohar @andreiko

**Comment by f2prateek** [comment]
also cc @dominicbarnes from https://github.com/segmentio/objects-go/issues/6

**Comment by tejasmanohar** [comment]
LGTM, thanks @patrickmcguire

**Pull request merged**
